-- AlterTable
ALTER TABLE "Project" ALTER COLUMN "keywords" SET NOT NULL,
ALTER COLUMN "keywords" SET DATA TYPE TEXT,
ALTER COLUMN "channels" SET NOT NULL,
ALTER COLUMN "channels" SET DATA TYPE TEXT,
ALTER COLUMN "format" SET NOT NULL,
ALTER COLUMN "format" SET DATA TYPE TEXT;
